apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uv5op94c5-go
  janus-idp.io/tekton: uv5op94c5-go
  backstage.io/kubernetes-id: uv5op94c5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uv5op94c5-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
