apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uv5op94c5-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uv5op94c5-go 
  name: uv5op94c5-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uv5op94c5-go 
